routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*Route::get('/', function () {
    return view('welcome');
});*/
//administrador
/*Route::get('/admin', function(){
  return view('dashboard.sectionadmin');
});*/

Auth::routes();

Route::group(['middleware'=>'auth'], function() {
   //Dashboard
	//-gestion de noticias
	Route::get('Dashboard/Noticias', 'Dashboard\NewsAdminController@index')->name('path_noticias');
	Route::name('crearnoticia')->get('Dashboard/createNew', 'Dashboard\NewsAdminController@create');
	Route::name('guardarnoticia')->post('Dashboard/noticias', 'Dashboard\NewsAdminController@store');
	Route::name('vernoticia')->get('/Dashboard/New/{new}', 'Dashboard\NewsAdminController@show');
	Route::name('editarnoticia')->get('/Dashboard/New/{new}/edit','Dashboard\NewsAdminController@edit');
	Route::name('actualizarnoticia')->put('/Dashboard/New/{new}','Dashboard\NewsAdminController@update');
	Route::name('eliminarnoticia')->delete('Dashboard/New/{new}/delete', 'Dashboard\NewsAdminController@delete');
    //-gestion categorias
    Route::get('Dashboard/Categorias', 'Dashboard\CategoriesAdminController@index')->name('path_categorias');
    Route::get('Dashboard/Categorias/crear', 'Dashboard\CategoriesAdminController@create')->name('crear_categoria');
    Route::post('Dashboard/Categorias', 'Dashboard\CategoriesAdminController@store')->name('guardar_nueva_categoria');
    Route::get('Dashboard/Categorias/{id}', 'Dashboard\CategoriesAdminController@show')->name('ver_categoria');
    Route::get('Dashboard/Categoria/{id}/editar', 'Dashboard\CategoriesAdminController@edit')->name('editar_categoria');
    Route::put('Dashboard/Categoria/{id}', 'Dashboard\CategoriesAdminController@update')->name('actualizar_categoria');
    /*Route::delete('Dashboard/Categoria/{id}/eliminar', 'Dashboard\CategoriesAdminController@destroy')->name('eliminar_categoria');*/
    
    //gestion anuncios (ads)
    Route::resource('/Dasboard/Ads', 'Dashboard\AdsController');

});

Route::group(['middleware'=>'setLocale'], function() {

    Route::get('Taragui/Admin', 'HomeController@index')->name('home');

    /******PUBLIC*********/
    Route::get('/', 'NewsController@index')->name('new_path');
    Route::get('/resultado', 'NewsController@query')->name('path_result_new');


    /*Route::name('detalle')->get('/Noticias/{new}', 'NewsController@show');*/

    Route::put('/banner-horizontal', 'NewsController@banner')->name('new_banner_hor');
    Route::put('/banner-horizontal2', 'NewsController@banner2')->name('new_banner_hor2');


    //ruta dinamica para cada categoria 
    Route::get('/Categoria/{name}', 'NewsController@categoria')->name('path_categoria');
    //mostrar categoria
    Route::get('/Categoria/{name?}/{id}', 'NewsController@show_categoria')->name('cat_detalle');


    //imagen cabecera
    Route::put('/imagen-cabecera', 'NewsController@imgHeader')->name('imagen_cabecera');

    //historial de noticias por año y por mes del año
    Route::get('historial-noticias/{year}', 'NewsController@getNewsYear')->name('getNewsYear');
    Route::get('historial-noticias/{month}/{year}', 'NewsController@getNewsMonthYear')->name('getNewsMonthYear');
    Route::get('historial-noticias', 'NewsController@getNewsHistory')->name('historial-noticias');
});



//view composer
View::composer('*', function($view)
{
    $sharefab = 0;
    $sharetwi = 0;
    $sharewha = 0;
    $shareimg = 0;
   $view->with(['shareimg'=>$shareimg,
   'sharefab'=>$sharefab, 'sharetwi'=>$sharetwi, 'sharewha'=>$sharewha]);
});

resources/views/dashboard/section/anuncios/formulario.blade.php
@extends('dashboard._app_wrapper')
@section('body')
@if ($data->exists)
  <form action="{{ route('Ads.update', ['id'=>$data->id]) }}" method="POST" role="form" enctype="multipart/form-data">
    {{ method_field('PUT') }}
    <legend>Editar Anuncio</legend>
@else
  <legend>Crear Anuncio</legend>
 <form action="{{ route('Ads.store') }}" method="POST" role="form" enctype="multipart/form-data">
@endif
{{ csrf_field() }}
  	<div class="form-group">
  		<label for="nombre">Nombre</label>
  		<input type="text" class="form-control" id="nombre" name="nombre" placeholder="nombre" value="{{ $data->nombre or old('nombre') }}">
  	</div><hr>
    @if ($data->imagen)
          <strong>Imagen actual:</strong>
          <img src="{{ url('imagenes_anuncios/'. $data->imagen) }}" alt="imagen_anuncio_actual" width="100" height="100">{{ $data->imagen }}
    @endif
    <br>
    <label for="imagen-ads">Imagen del anuncio</label>
    <input type="file" accept="image/png, image/jpeg" name="imagen-ads" id="imagen-ads"/>
    <hr>
    <div class="col-md-offset-5">
      <button type="submit" class="btn btn-primary">Guardar</button>
      <a href="{{ route('Ads.index') }}" title="volver" class="btn btn-primary">Volver</a>
    </div>
  	
  </form>
@endsection

resources/views/dashboard/section/anuncios/index.blade.php
@extends('dashboard._app_wrapper')
@section('body')
<legend>Anuncios</legend>
<div class="pull-right">
	<a id="btn-crear-categoria" class="btn btn-primary" href="{{ route('Ads.create') }}" title="">Crear Anuncio</a>
</div>
<br>
<table class="table table-striped table-hover">
	<thead>
		<tr>
			<th>Id</th>
			<th>Creado</th>
            <th>Actualizado</th>
            <th>Nombre</th>
            <th>Imagen</th>
			<th>Accion</th>
		</tr>
	</thead>
	<tbody>
		@forelse ($ads as $data)
	    <tr>
			<td>{{ $data->id }}</td>
			<td>{{ $data->created_at }}</td>
			<td>{{ $data->updated_at }}</td>
			<td>{{ $data->nombre }}</td>
			<td>{{ $data->imagen }}</td>
			<td>
			    <div class="btn-group">
						<a class="btn btn-link" href="{{ route('Ads.show', ['id' => $data->id]) }}" title="ver"><span class="glyphicon glyphicon-file" aria-hidden="true"></span>
						</a>
						<a class="btn btn-link" href="{{ route('Ads.edit', ['id' => $data->id ]) }}" title="editar"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
						</a>
						<form action="{{ route('Ads.destroy', ['id'=>$data->id]) }}" method="POST" role="form">
              			 	{{ csrf_field() }} {{ method_field('DELETE')}}
							<button type="submit" class="btn btn-link" title="eliminar">
								<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
							</button>
						</form>
					</div>
				</td>
			@empty
			<th> Sin datos</th>
		@endforelse
	    </tr>
	</tbody>
</table>

  
  
@stop

resources/views/dashboard/section/anuncios/show.blade.php
@extends('dashboard._app_wrapper')
@section('body')
<br>
<a href="{{ route('Ads.index') }}" class="pull-right btn btn-primary" title="volver">Volver</a>
<hr>
<h1>{{ $ads->nombre }}</h1>
  <p>{{ $ads->imagen }}</p>
  <img src="{{ url('imagenes_anuncios/'.$ads->imagen)}}" alt="imagen_ads_admin" style="border: 1px solid grey">
@endsection